import assert from 'node:assert/strict';
import app from './game.js';
const required = ['createInitialState', 'addTask', 'toggleTask', 'removeTask', 'clearCompleted', 'filterTasks'];
for (const name of required) assert.equal(typeof app[name], 'function', `${name} must be exported`);
let state = app.createInitialState();
assert.deepEqual(state.tasks, []);
state = app.addTask(state, 'Write release notes');
state = app.addTask(state, 'Review evidence');
assert.equal(state.tasks.length, 2);
assert.equal(state.tasks[0].text, 'Write release notes');
assert.ok(state.tasks[0].id !== state.tasks[1].id);
const firstId = state.tasks[0].id;
const secondId = state.tasks[1].id;
state = app.toggleTask(state, firstId);
assert.equal(state.tasks.find(task => task.id === firstId).completed, true);
assert.deepEqual(app.filterTasks(state, 'completed').map(task => task.id), [firstId]);
assert.deepEqual(app.filterTasks(state, 'active').map(task => task.id), [secondId]);
assert.equal(app.filterTasks(state, 'all').length, 2);
state = app.clearCompleted(state);
assert.deepEqual(state.tasks.map(task => task.id), [secondId]);
state = app.removeTask(state, secondId);
assert.equal(state.tasks.length, 0);
console.log('controller-owned focus-board mechanics passed');
